tech_corp_front_homepage:
    path:     /
    defaults: { _controller: TechCorpFrontBundle:Static:homepage }
tech_corp_front_about:
    path:     /about
    defaults: { _controller: TechCorpFrontBundle:Static:about }
