tech_corp_front_security_login:
    path:     /secured/login
    defaults: { _controller: TechCorpFrontBundle:Security:login }

tech_corp_front_security_secured:
    path:     /secured/secured
    defaults: { _controller: TechCorpFrontBundle:Security:secured }

tech_corp_front_security_login_check:
    path:     /secured/login_check

tech_corp_front_security_logout:
    path:     /secured/logout