TechCorpFrontBundle_status:
    resource: "@TechCorpFrontBundle/Resources/config/routing/status.yml"
    prefix:   /status

tech_corp_front:
    resource: "@TechCorpFrontBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
